main: me.Woool.FishingQuest.Main
version: 1.8.8
name: FishingQuest

commands:
   fishingquest:
      description: Initializes the fishing quest for a player
      usage: /fishingquest (No arguments required)	
   fcreate:
      description: (AdminCommand) Creates the 'placeholders' for the fishing quest
      usage: /fcreate [a,b,return,fish]
  
